user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name attacker.test;

        location / {
            proxy_pass http://site1;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto http;
        }
    }

    server {
        listen 80;
        server_name adition.com;

        location / {
            proxy_pass http://site2;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto http;
            proxy_set_header X-Referer $http_referer;
        }
    }

    server {
        listen 80;
        server_name leak.test;

        location / {
            proxy_pass http://site3;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto http;
        }
    }

    server {
        listen 443 ssl;
        server_name attacker.test;

        ssl_certificate     /certs/leak.test+2.pem;
        ssl_certificate_key /certs/leak.test+2-key.pem;

        location / {
            proxy_pass http://site1;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
        }
    }

    server {
        listen 443 ssl;
        server_name adition.com;

        ssl_certificate     /certs/leak.test+2.pem;
        ssl_certificate_key /certs/leak.test+2-key.pem;

        location / {
            proxy_pass http://site2;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Referer $http_referer;
        }
    }

    server {
        listen 443 ssl;
        server_name leak.test;

        ssl_certificate     /certs/leak.test+2.pem;
        ssl_certificate_key /certs/leak.test+2-key.pem;

        location / {
            proxy_pass http://site3;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}
